blank_issues_enabled: false
contact_links:
  - name: Customer support
    url: mailto:ontherisedigital@gmail.com
    about: Bought Color Palette PRO and need help? Email us. Please don't open an issue.
